/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 13.0 		*/
/*  Created On : 21-Apr-2021 17:07:43 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Sequences for Autonumber Columns */


/* Drop Tables */

DROP TABLE IF EXISTS activity CASCADE
;

DROP TABLE IF EXISTS activity_log CASCADE
;

DROP TABLE IF EXISTS category CASCADE
;

DROP TABLE IF EXISTS daily_notes CASCADE
;

DROP TABLE IF EXISTS emotion_daily_notes CASCADE
;

DROP TABLE IF EXISTS emotions CASCADE
;

DROP TABLE IF EXISTS habit_week_goal CASCADE
;

DROP TABLE IF EXISTS person CASCADE
;

/* Create Tables */

CREATE TABLE activity
(
	id bigserial NOT NULL,
	person_id bigint NOT NULL,
	type char(1) NOT NULL,    -- H) Habit T) Task E) Event
	name varchar(50) NOT NULL,
	category_id bigint NULL,
	notes text NULL,
	measure_type varchar(2) NULL,    -- SE) Tracked (start and end time) D) Duration Q) Quantity N) Just 'Done'
	reminder integer NULL,    -- In minutes
	active BOOLEAN DEFAULT (TRUE)
)
;

CREATE TABLE activity_log
(
	id bigserial NOT NULL,
	activity_id bigint NULL,
	status smallint NULL,
	date1 date NULL,
	date_precision char(1) NULL,    -- This is used for tasks only.  Specify that the date is related to:  M) Month W) Week D) Day
	duration numeric(8,2) NULL,    -- duration of the activity measure
	start_time time without time zone NULL,    -- Actual start time of the activity measure
	end_time time without time zone NULL,    -- Actual end time of the activity measure
	quantity numeric(8,2) NULL,    -- Quantity of the activity measure
	emotion_id smallint NULL,      -- emotion_activity_log: emotion weight
	notes text NULL
)
;


CREATE TABLE category
(
	id bigserial NOT NULL,
	name varchar(50) NOT NULL,
	person_id integer NOT NULL,
	parent_id bigint NULL    -- For when it is a sub category
)
;

CREATE TABLE daily_notes
(
	id bigserial NOT NULL,
	date varchar(50) NOT NULL,
	notes text NOT NULL,
	person_id integer NOT NULL,
	category_id integer NULL
)
;


CREATE TABLE emotion_daily_notes
(
	emotion_id integer NOT NULL,
	daily_notes_id integer NOT NULL
)
;

CREATE TABLE emotions
(
	id serial NOT NULL,
	name varchar(50) NOT NULL
)
;

CREATE TABLE habit_week_goal
(
	activity_id bigint NOT NULL,    -- Id do habit
	week date NOT NULL,
	measure numeric(8,2) NULL,
	measure_type varchar(2) NULL   --  D) Duration Q) Quantity F) Frequency

)
;

CREATE TABLE person
(
	id bigint NOT NULL,
	name varchar(100) NOT NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE activity ADD CONSTRAINT PK_schedule
	PRIMARY KEY (id)
;

CREATE INDEX IXFK_schedule_person ON activity (person_id ASC)
;

CREATE INDEX IXFK_schedule_schedule_category ON activity (category_id ASC)
;

ALTER TABLE activity_log ADD CONSTRAINT PK_schedule_log
	PRIMARY KEY (id)
;


CREATE INDEX IXFK_schedule_log_schedule ON activity_log (activity_id ASC)
;


ALTER TABLE category ADD CONSTRAINT PK_schedule_category
	PRIMARY KEY (id)
;

ALTER TABLE daily_notes ADD CONSTRAINT PK_daily_notes
	PRIMARY KEY (id)
;

CREATE INDEX IXFK_daily_notes_activity_category ON daily_notes (category_id ASC)
;

CREATE INDEX IXFK_daily_notes_person ON daily_notes (person_id ASC)
;


CREATE INDEX IXFK_activity_log_emotions ON activity_log (emotion_id ASC)
;

ALTER TABLE emotion_daily_notes ADD CONSTRAINT PK_emotion_daily_notes
	PRIMARY KEY (emotion_id,daily_notes_id)
;

CREATE INDEX IXFK_emotion_daily_notes_daily_notes ON emotion_daily_notes (daily_notes_id ASC)
;

CREATE INDEX IXFK_emotion_daily_notes_emotions ON emotion_daily_notes (emotion_id ASC)
;

ALTER TABLE emotions ADD CONSTRAINT PK_emotions
	PRIMARY KEY (id)
;

ALTER TABLE habit_week_goal ADD CONSTRAINT PK_habit_weekly_goal
	PRIMARY KEY (activity_id,week)
;

CREATE INDEX IXFK_habit_week_goal_activity ON habit_week_goal (activity_id ASC)
;

ALTER TABLE person ADD CONSTRAINT PK_person
	PRIMARY KEY (id)
;

/* Create Foreign Key Constraints */

ALTER TABLE activity ADD CONSTRAINT FK_schedule_person
	FOREIGN KEY (person_id) REFERENCES person (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE activity ADD CONSTRAINT FK_schedule_schedule_category
	FOREIGN KEY (category_id) REFERENCES category (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE activity_log ADD CONSTRAINT FK_schedule_log_schedule
	FOREIGN KEY (activity_id) REFERENCES activity (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE daily_notes ADD CONSTRAINT FK_daily_notes_activity_category
	FOREIGN KEY (category_id) REFERENCES category (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE daily_notes ADD CONSTRAINT FK_daily_notes_person
	FOREIGN KEY (person_id) REFERENCES person (id) ON DELETE No Action ON UPDATE No Action
;


ALTER TABLE activity_log ADD CONSTRAINT FK_activity_log_emotions
	FOREIGN KEY (emotion_id) REFERENCES emotions (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE emotion_daily_notes ADD CONSTRAINT FK_emotion_daily_notes_daily_notes
	FOREIGN KEY (daily_notes_id) REFERENCES daily_notes (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE emotion_daily_notes ADD CONSTRAINT FK_emotion_daily_notes_emotions
	FOREIGN KEY (emotion_id) REFERENCES emotions (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE habit_week_goal ADD CONSTRAINT FK_habit_week_goal_activity
	FOREIGN KEY (activity_id) REFERENCES activity (id) ON DELETE No Action ON UPDATE No Action
;

/* Create Table Comments, Sequences for Autonumber Columns */

COMMENT ON COLUMN activity.type
	IS 'H) Habit T) Task E) Event'
;

COMMENT ON COLUMN activity.measure_type
	IS 'SE) Tracked (start and end time) D) Duration Q) Quantity N) Just Done'
;

COMMENT ON COLUMN activity.reminder
	IS 'In minutes'
;

COMMENT ON COLUMN activity_log.status
	IS '1) Pending 2) Complete 3) Complete - arrived late
        4) Canceled 5) Canceled by me 6) Rescheduled/Passed over
'
;



COMMENT ON COLUMN activity_log.date_precision
	IS 'This is used for tasks only.  Specify that the date is related to:  M) Month W) Week D) Day T) Task Pool'
;


COMMENT ON COLUMN activity_log.duration
	IS 'duration of the activity measure'
;

COMMENT ON COLUMN activity_log.start_time
	IS 'Actual start time of the activity measure'
;

COMMENT ON COLUMN activity_log.end_time
	IS 'Actual end time of the activity measure'
;

COMMENT ON COLUMN activity_log.quantity
	IS 'Quantity of the activity measure'
;


COMMENT ON COLUMN category.parent_id
	IS 'For when it is a sub category'
;




COMMENT ON COLUMN habit_week_goal.activity_id
	IS 'Id do habit'
;

insert into emotions (id, name)
values (-3, 'Rock bottom'),
       (-2, 'Frustrated'),
       (-1, 'Disappointed'),
       ( 0, 'Ok'),
       ( 1, 'Happy'),
       ( 2, 'Excited'),
       ( 3, 'Over the moon');



